// English translation
R.registerLocale('en-GB', 
{
  'language': "Language",
  'contactstr': "Contact me",
  'educationstr': "Education",
  'certificationsstr': "Certifications",
  'portfoliostr': "Portfolio",
  'skillsstr': "Skills",
  'experiencestr': "Experience",
  'subtitle': "I.T. Student and Enthusiast",
  'educationheader': "Education",
  'skillsheader': "Skills",
  'unibobachelor': "Bachelor degree in Computer Science and Engineering",
  'unipvmaster': "Master degree in Computer Engineering",
  'highschool': "Graduation in Computer Science at IISS G. Salvemini Alessano",
  'comptia': "CompTia Security+ Certification",
  'efsetc1': "English EFset C1 Certification Dublin",
  'pet': "English PET Cambridge Certification",
  'gese': "English Trinity Gese level 9 Certification",
  'netmanager': "Network management",
  'androiddev': "Android Apps Development",
  'infsec': "Information Security",
  'expheader': "Experience",
  'ittech': "I.T. Consultant - University internship",
  'datagarmon': "June 2015 - September 2015",
  'portfheader': "Portfolio",
  'contheader': "Contact me",
  'gesttitle': "Dev. of a web-based management software for the textile sector",
  'gestfeatures': "<li>Warehouse management</li><li>Customer and Products registry</li><li>Creation and management of orders</li><li>Real-time summary of the manufacturing process</li>",
  'cmstitle': "Management and development of CMS based websites",
  'androidappsubtitle': "By the use of the Cordova framework",
  'androidapptitle': "Development and publication of a non-native Android app",
  'message': "Message",
  'accessibility': "Accessibility",
  'subbutton': "<input type='submit' value='Send'>",
  'nodeprojs': "Development of small web-apps (Based on JS ES6 Front-end and Node.js Back-end)"

});
