// English translation
R.registerLocale('en-GB', 
{
  'language': "Language",
  'contactstr': "Contact me",
  'educationstr': "Education",
  'certificationsstr': "Certifications",
  'portfoliostr': "Portfolio",
  'skillsstr': "Skills",
  'experiencestr': "Experience",
  'subtitle': "I.T. Student and Enthusiast",
  'educationheader': "Education",
  'skillsheader': "Competenze",
  'unibobachelor': "Bachelor degree in Computer Science and Engineering",
  'unipvmaster': "Master degree in Computer Engineering",
  'highschool': "Graduation in Computer Science at IISS G. Salvemini Alessano",
  'comptia': "CompTia Security+ Certification",
  'efsetc1': "English EFset C1 Certification Dublin",
  'pet': "English PET Cambridge Certification",
  'gese': "English Trinity Gese level 9 Certification",
  'netmanager': "Network management",
  'androiddev': "Android Apps Development",
  'infsec': "Information Security",
});
