// English translation
R.registerLocale('it-IT',
{
  'language': "Lingua",
  'contactstr': "Contattami",
  'educationstr': "Educazione",
  'certificationsstr': "Certificazioni",
  'portfoliostr': "Portfolio",
  'skillsstr': "Competenze",
  'experiencestr': "Esperienza",
  'subtitle': "AWS Cloud Solutions Architect ed appassionato di tecnologie Serverless",
  'educationheader': "Educazione",
  'skillsheader': "Competenze",
  'unibobachelor': "Laurea triennale in Ingegneria e Scienze informatiche",
  'unipvmaster': "Laurea magistrale in Computer Engineering",
  'highschool': "Perito Informatico IISS G. Salvemini Alessano",
  'comptia': "Certificazione CompTia Security+",
  'efsetc1': "Certificazione di Inglese EFset C1 Dublino",
  'pet': "Certificazione di Inglese PET Cambridge",
  'gese': "Certificazione di Inglese Trinity Gese livello 9",
  'netmanager': "Amministraz. di reti",
  'androiddev': "Sviluppo App Android",
  'infsec': "Sicurezza Informatica",
  'expheader': "Esperienza",
  'ittech': "Consulente Informatico - Tirocinio universitario",
  'datagarmon': "Giugno 2015 - Settembre 2015",
  'portfheader': "Portfolio",
  'contheader': "Contattami",
  'gesttitle': "Sviluppo di un gestionale web-based per il settore tessile",
  'gestfeatures': "<li>Gestione magazzini</li><li>Anagrafica clienti e prodotti</li><li>Creazione e gestione ordini</li><li>Prospetto avanzamento della lavorazione real-time</li>",
  'cmstitle': "Sviluppo e gestione di siti web basati su CMS",
  'androidappsubtitle': "Tramite l'utilizzo del framework Cordova",
  'androidapptitle': "Sviluppo e pubblicazione app Android non nativa",
  'message': "Messaggio",
  'accessibility': "Accessibilità",
  'subbutton': "<input type='submit' value='Invia'>",
  'nodeprojs': "Sviluppo di piccole web-app (Front-end JS ES6, Back-end in node)",
  'pythonprojs': "Sviluppo di software (Python con Serverless framework su AWS)",
  'telegrambottitle': "Telegram bot per riconoscimento facciale"
});
