// English translation
R.registerLocale('it-IT', 
{
  'language': "Lingua",
  'contactstr': "Contattami",
  'educationstr': "Educazione",
  'certificationsstr': "Certificazioni",
  'portfoliostr': "Portfolio",
  'skillsstr': "Competenze",
  'experiencestr': "Esperienza",
  'subtitle': "Studente ed appassionato di Informatica",
  'educationheader': "Educazione",
  'skillsheader': "Competenze",
  'experienceheader': "Esperienza",
  'unibobachelor': "Laurea triennale in Ingegneria e Scienze informatiche",
  'unipvmaster': "Laurea magistrale in Computer Engineering",
  'highschool': "Perito Informatico IISS G. Salvemini Alessano",
  'comptia': "Certificazione CompTia Security+",
  'efsetc1': "Certificazione di Inglese EFset C1 Dublino",
  'pet': "Certificazione di Inglese PET Cambridge",
  'gese': "Certificazione di Inglese Trinity Gese livello 9",
  'netmanager': "Amministrazione delle reti",
  'androiddev': "Sviluppo App Android",
  'infsec': "Sicurezza Informatica",

});
